# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BLYpRUqqXA4wCvzVAZI6-tsfV8TssNMu
"""

import matplotlib.pyplot as plt 
import numpy as np 

import subprocess
import shlex

plt.axis([0,6,-6,6])

plt.axis('on')

A = np.array([5,3])
C = np.array([1,-5])
B = np.array([5,-5])
P = np.array([3,-1])

def line_gen(A,B):
  len =10
  x_AB = np.zeros((2,len))
  lam_1 = np.linspace(0,1,len)
  for i in range(len):
    temp1 = A + lam_1[i]*(B-A)
    x_AB[:,i]= temp1.T
  return x_AB

x_AP = line_gen(A,P)
x_CP = line_gen(C,P)
x_BP = line_gen(B,P)

plt.plot(x_AP[0,:],x_AP[1,:],label='$AP$')
plt.plot(x_BP[0,:],x_BP[1,:],label='$BP$')
plt.plot(x_CP[0,:],x_CP[1,:],label='$CP$')


plt.xlabel('$x-axis$')
plt.ylabel('$y-axis$')

plt.text (5,3,'A(5,3)')
plt.text(5,-5,'B(5,-5)')
plt.text(1,-5,'C(1,-5)')
plt.text(3,-1,'P(3,-1)')
plt.legend(loc='best')
plt.grid() 
plt.axis('equal')

plt.show()